# Generated by Django 5.2.2 on 2025-06-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
                ('algorithm_version', models.CharField(max_length=50)),
                ('minimum_similarity_threshold', models.FloatField(default=0.3)),
                ('suspicious_threshold', models.FloatField(default=0.7)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
