# Generated by Django 5.2.2 on 2025-06-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-timestamp']},
        ),
    ]
